name: parliamentary_minutes
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
  - beautifulsoup4=4.11.1
  - pandas=1.4.2
  - numpy=1.22.3
  - matplotlib=3.5.2
  - seaborn=0.11.2
  - nltk=3.7
  - wordcloud=1.8.1
  - pytorch=1.10.2
  - datasets=2.2.2
  - transformers=4.19.2
  - gensim=4.2.0
  - scikit-learn=1.0.2
  - selenium=4.2.0
  - webdriver-manager=3.7.0
  - pdfplumber=0.7.0
